[project]
name = "agent-pydantic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "copilotkit>=0.1.54",
    "pydantic-ai>=0.8.0",
    "pydantic-ai-slim[ag-ui]>=0.8.0",
]
